#pragma once
// Lattice generated by a quad-I vector v1 and a quad-II vector v2: class keys, lattice points,
// representatives inside a region, and defects.
#include "array2d.hpp"
#include "instrument.hpp"
#include <unordered_map>
#include <optional>
#include <cstdlib>

namespace gp {

struct Lattice {
    Vec2 v1, v2;   // quad-I, quad-II
    long D = 0;    // cross(v1, v2) != 0
    Lattice() = default;
    Lattice(Vec2 a, Vec2 b) : v1(a), v2(b), D(cross(a, b)) {}
    // u = (a/D) v1 + (b/D) v2; the class of u is (a mod |D|, b mod |D|).
    std::pair<long, long> key(Vec2 u) const {
        long a = (long)u.r * v2.c - (long)u.c * v2.r;
        long b = (long)v1.r * u.c - (long)v1.c * u.r;
        long M = std::labs(D);
        a %= M; if (a < 0) a += M;
        b %= M; if (b < 0) b += M;
        return {a, b};
    }
    std::uint64_t key64(Vec2 u) const {
        auto [a, b] = key(u);
        return (std::uint64_t)a * (std::uint64_t)std::labs(D) + (std::uint64_t)b;
    }
    bool is_lattice_point(Vec2 u) const { auto [a, b] = key(u); return a == 0 && b == 0; }
    bool congruent(Vec2 u, Vec2 w) const { return key(u) == key(w); }
    // Lemma 6 covering condition for a rectangle of rows x cols.
    bool covered_by(int rows, int cols) const {
        int r1 = v1.r, c1 = v1.c, r2 = iabs(v2.r), c2 = v2.c;
        return (imax(r1, r2) <= rows && c1 + c2 <= cols) || (r1 + r2 <= rows && imax(c1, c2) <= cols);
    }
};

// One representative point per lattice class inside a region.
struct RepMap {
    std::unordered_map<std::uint64_t, Vec2> rep;
    static RepMap build(const Lattice& L, const View& region) {
        RepMap m;
        for (int r = region.r0; r < region.r0 + region.size; ++r)
            for (int c = region.c0; c < region.c0 + region.size; ++c)
                m.rep.try_emplace(L.key64({r, c}), Vec2{r, c});
        return m;
    }
    template <class It>
    static RepMap build(const Lattice& L, It first, It last) {
        RepMap m;
        for (; first != last; ++first) m.rep.try_emplace(L.key64(*first), *first);
        return m;
    }
    std::optional<Vec2> find(const Lattice& L, Vec2 u) const {
        auto it = rep.find(L.key64(u));
        if (it == rep.end()) return std::nullopt;
        return it->second;
    }
};

// Defects of the view cur with respect to the lattice of the (lattice-generative) view prev.
struct DefectGrid {
    View cur;
    std::vector<char> grid;      // cur.size^2, 1 = defect
    std::vector<Vec2> list;
    bool is_defect(Vec2 p) const {
        if (!cur.contains(p)) return false;
        Vec2 q = cur.local(p);
        return grid[(std::size_t)q.r * cur.size + q.c] != 0;
    }
};

template <class T>
DefectGrid find_defects(const Array2D<T>& A, const View& cur, const View& prev, const Lattice& L) {
    DefectGrid g; g.cur = cur; g.grid.assign((std::size_t)cur.size * cur.size, 0);
    RepMap reps = RepMap::build(L, prev);
    for (int r = cur.r0; r < cur.r0 + cur.size; ++r)
        for (int c = cur.c0; c < cur.c0 + cur.size; ++c) {
            Vec2 u{r, c};
            auto rep = reps.find(L, u);
            if (!gp_check(rep.has_value(), "Lemma6:representative")) continue;
            if (!(A.at(u) == A.at(*rep))) {
                Vec2 q = cur.local(u);
                g.grid[(std::size_t)q.r * cur.size + q.c] = 1;
                g.list.push_back(u);
            }
        }
    return g;
}

} // namespace gp
